#os:
#  - osx

language: node_js

node_js:
  - 8

env:
  - CXX=g++-4.8

script: ./script/travis.sh

branches:
  only:
  - master

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
